/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const LOCALIZATION = {
  en: {
    appTitle: 'Pakistan Legal Guidance Assistant',
    appSubtitle: 'Interactive legal information, statutory analysis, and next steps under Pakistani Law',
    navAssistant: 'Legal Assistant',
    navTopics: 'Browse Guides',
    navDictionary: 'Legal Dictionary',
    newConsultation: 'New Consultation',
    pastConsultations: 'Past Consultations',
    emptyHistory: 'No past consultations yet.',
    suggestedScenarios: 'Suggested Scenarios',
    inputPlaceholder: 'Describe your legal problem in detail (e.g., land disputes, child custody, online harassments)...',
    sendButton: 'Analyze & Advise',
    sendActive: 'Analyzing...',
    warningDisclaimerTitle: 'Professional Advisor Disclaimer',
    warningDisclaimerText: 'This AI Assistant provides information and suggested courses of action under Pakistani Law for educational and guidance purposes. It is NOT legal advice. Laws can be complex and situational. Always consult a registered Advocate of High Court / District Court before taking official action.',
    identifiedDomains: 'Identified Legal Domains',
    applicableStatutes: 'Relevant Acts & Sections (Pakistan)',
    actionableAvenues: 'Suggested Legal Avenues & Next Steps',
    explanationTitle: 'Legal Scenario Analysis',
    noMessagesYet: 'Type your legal query below, or choose one of our predefined legal guides in the list!',
    errorMissingKey: 'GEMINI_API_KEY is not configured. Please use the Secrets panel to configure your key.',
    errorTitle: 'Incomplete Assessment',
    searchDictionary: 'Search legal terms (e.g. FIR, Khula, Mehr)...',
    termContext: 'Statutory Context in Pakistan',
    allTerms: 'All Legal Terms',
    guidebookTitle: 'Pakistani Legal Guidebooks',
    guidebookSubtitle: 'Select a domain to inspect relevant legislations, codes, and pre-packaged sample templates.',
    governingActs: 'Governing Acts & Ordinances',
    cloverHelperTitle: 'Common Legal Terms Helper',
    cloverHelperSub: 'Click any word to add to your query:',
    tryThisTemplate: 'Try this template',
    clarificationText: 'The assistant requested more details before offering a legal pathway. Please reply directly with the requested specifications.',
  },
  ur: {
    appTitle: 'پاکستانی قانونی رہنمائی اسسٹنٹ',
    appSubtitle: 'پاکستانی قوانین کے تحت انٹرایکٹو قانونی معلومات، دفعات کا تجزیہ اور عملی اقدامات',
    navAssistant: 'قانونی مددگار',
    navTopics: 'مجوزہ کتابچے',
    navDictionary: 'قانونی لغت',
    newConsultation: 'نیا مشورہ',
    pastConsultations: 'پچھلے مشورے',
    emptyHistory: 'ابھی تک کوئی سابقہ مشورہ ریکارڈ نہیں کیا گیا۔',
    suggestedScenarios: 'تجویز کردہ حالات و سوالات',
    inputPlaceholder: 'اپنا قانونی مسئلہ تفصیل سے لکھیں (مثلاً جائیداد کا تنازعہ، بچے کی حضانت، آن لائن ہراسگی)...',
    sendButton: 'تجزیہ اور حل حاصل کریں',
    sendActive: 'تجزیہ جاری ہے...',
    warningDisclaimerTitle: 'پیشہ ورانہ قانونی مشورے کی تنبیہ',
    warningDisclaimerText: 'یہ مصنوعی ذہانت (AI) اسسٹنٹ پاکستانی قانون کے تحت صرف معلومات اور ممکنہ راستوں کی نشاندہی کرتا ہے۔ یہ کوئی سرکاری یا پیشہ ورانہ قانونی مشورہ نہیں ہے۔ قوانین پیچیدہ ہو سکتے ہیں، اس لیے عملی کارروائی سے پہلے ہمیشہ ہائی کورٹ یا ضلعی عدالت کے رجسٹرڈ وکیل (ایڈووکیٹ) سے رجوع کریں۔',
    identifiedDomains: 'نشاندہی شدہ قانونی زمرہ جات',
    applicableStatutes: 'متعلقہ ایکٹس اور تعزیراتِ پاکستان دفعات',
    actionableAvenues: 'تجویز کردہ قانونی حل اور اگلے اقدامات',
    explanationTitle: 'قانونی صورتحال کا تجزیہ',
    noMessagesYet: 'نیچے لکھ کر اپنا قانونی مسئلہ بیان کریں، یا بائیں ہاتھ پر موجود کسی زمرے اور ٹیمپلیٹ کا انتخاب کریں!',
    errorMissingKey: 'جیمنی API کی موجود نہیں ہے۔ براہ کرم اسے فعال کریں۔',
    errorTitle: 'نامکمل قانونی جائزہ',
    searchDictionary: 'قانونی اصطلاحات تلاش کریں (جیسے ایف آئی آر، خلع، مہر)...',
    termContext: 'پاکستان میں قانونی حیثیت',
    allTerms: 'تمام اصطلاحات',
    guidebookTitle: 'پاکستانی قانونی رہنما کتابچے',
    guidebookSubtitle: 'قوانین، دفعات اور پہلے سے تیار شدہ سوالاتی ٹیمپلیٹس کا مطالعہ کرنے کے لیے زمرہ منتخب کریں۔',
    governingActs: 'حکمران قوانین اور آرڈیننس',
    cloverHelperTitle: 'بنیادی قانونی الفاظ مددگار',
    cloverHelperSub: 'اپنے سوال میں شامل کرنے کے لیے کسی لفظ پر کلک کریں:',
    tryThisTemplate: 'ٹیمپلیٹ آزمائیں',
    clarificationText: 'اسسٹنٹ نے کوئی حتمی مشورہ دینے سے پہلے کچھ مزید تفصیلات پوچھی ہیں۔ براہ کرم ان کا جواب دیں۔',
  },
};

export const COMMON_URDU_WORDS = [
  { word: 'خلع', en: 'Khula' },
  { word: 'طلاق', en: 'Talaq' },
  { word: 'ایف آئی آر', en: 'FIR' },
  { word: 'بچے کی حضانت', en: 'Child Custody' },
  { word: 'حق مہر', en: 'Mehr' },
  { word: 'قبضہ', en: 'Land Grabbing' },
  { word: 'جائیداد', en: 'Property' },
  { word: 'وارثان', en: 'Heirs' },
  { word: 'خرچہ', en: 'Maintenance' },
  { word: 'معاہدہ', en: 'Contract' },
  { word: 'پولیس', en: 'Police' },
  { word: 'ایف آئی اے', en: 'FIA' },
  { word: 'صارف عدالت', en: 'Consumer Court' },
  { word: 'لیبر کورٹ', en: 'Labour Court' },
  { word: 'ضمانت', en: 'Bail' },
];
